name: Expo Web Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Expo Web Export
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout Code
        uses: actions/checkout@v4

      - name: 🧼 Clean Up Lock Conflicts
        run: |
          rm -f yarn.lock  # Remove if it exists to avoid conflicts

      - name: ⚙️ Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: 📦 Install Dependencies
        run: |
          npm install
          npm install react-native-web@~0.19.6 react-dom@18.2.0 @expo/webpack-config@^19.0.0

      - name: 🔧 Fix Mismatched Expo Deps
        run: npx expo install --fix

      - name: 🧪 Run Expo Doctor
        run: npx expo-doctor || true  # Allow soft warnings without failing

      - name: 🏗️ Build Web App
        run: npx expo export:web

      - name: 📁 Upload Web Build
        uses: actions/upload-artifact@v4
        with:
          name: expo-web-build
          path: dist/